copy C:\Work\git\DS_Projects\HostServer\src\*.java "C:\Users\user1\Google Drive\School\Courses\DistributedSystems-435\HostServer"
copy C:\Work\git\DS_Projects\HostServer\*.txt "C:\Users\user1\Google Drive\School\Courses\DistributedSystems-435\HostServer"
copy C:\Work\git\DS_Projects\HostServer\*.html "C:\Users\user1\Google Drive\School\Courses\DistributedSystems-435\HostServer"
copy C:\Work\git\DS_Projects\HostServer\*.bat "C:\Users\user1\Google Drive\School\Courses\DistributedSystems-435\HostServer"
copy C:\Work\git\DS_Projects\HostServer\*.csv "C:\Users\user1\Google Drive\School\Courses\DistributedSystems-435\HostServer"
