copy C:\Users\Joe\git\DS_Projects\Mimer\src\*.java "C:\Users\Joe\Google Drive\School\Courses\DistributedSystems-435\Mimer"
copy C:\Users\Joe\git\DS_Projects\Mimer\*.txt "C:\Users\Joe\Google Drive\School\Courses\DistributedSystems-435\Mimer"
copy C:\Users\Joe\git\DS_Projects\Mimer\*.html "C:\Users\Joe\Google Drive\School\Courses\DistributedSystems-435\Mimer"
copy C:\Users\Joe\git\DS_Projects\Mimer\*.bat "C:\Users\Joe\Google Drive\School\Courses\DistributedSystems-435\Mimer"
copy C:\Users\Joe\git\DS_Projects\Mimer\*.ico "C:\Users\Joe\Google Drive\School\Courses\DistributedSystems-435\Mimer"
copy C:\Users\Joe\git\DS_Projects\Mimer\*.xy1 "C:\Users\Joe\Google Drive\School\Courses\DistributedSystems-435\Mimer"
copy C:\Users\Joe\git\DS_Projects\Mimer\*.xyz "C:\Users\Joe\Google Drive\School\Courses\DistributedSystems-435\Mimer"
copy C:\Users\Joe\git\DS_Projects\Mimer\*.jar "C:\Users\Joe\Google Drive\School\Courses\DistributedSystems-435\Mimer"
